/*
 * config.h
 *
 *  Created on: 2 Feb 2019
 *      Author: alxhoff
 */

#ifndef CONFIG_H_
#define CONFIG_H_

//SCREEN
#define SCREEN_CURSOR_PERIOD	750
#define SSD1306_I2C_PORT		hi2c2

//RTC
#define RTC_DEF_TWELVE_HR	TRUE
#define RTC_DEF_HOUR		11
#define RTC_DEF_MIN			59
#define RTC_DEF_SEC			50
#define RTC_DEF_AM_PM		PM
#define RTC_DEF_WEEKDAY		1
#define RTC_DEF_DATE		05
#define RTC_DEF_MONTH		06
#define RTC_DEF_YEAR		2017
#define RTC_DEF_I2C			&hi2c2

//SHIFT
#define SHIFT_DEVICES		2
#define SHIFT_SER_IN_PORT	SHIFT_SER_DAT_GPIO_Port
#define SHIFT_SER_IN_PIN	SHIFT_SER_DAT_Pin
#define SHIFT_SER_CLK_PORT	SHIFT_SER_CLK_GPIO_Port
#define SHIFT_SER_CLK_PIN	SHIFT_SER_CLK_Pin
#define SHIFT_LATCH_PORT	SHIFT_LATCH_GPIO_Port
#define SHIFT_LATCH_PIN		SHIFT_LATCH_Pin
#define SHIFT_OUT_ENA_PORT	SHIFT_ENA_GPIO_Port
#define SHIFT_OUT_ENA_PIN	SHIFT_ENA_Pin
#define SHIFT_SER_CLR_PORT	SHIFT_CLR_GPIO_Port
#define SHIFT_SER_CLR_PIN	SHIFT_CLR_Pin

//NIXIES
#define NIXIE_DEVICES		2

#endif /* CONFIG_H_ */
