M48
; DRILL file {KiCad (6.0.5)} date Di 31 Mai 2022 00:34:22 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-31T00:34:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X108.203Y-65.194
X108.203Y-109.194
X202.203Y-65.194
X202.203Y-109.194
T2
X140.583Y-90.644
T0
M30
